import { NextRequest, NextResponse } from 'next/server';
import { getCached, setCached, hashPayload } from '@/lib/cache';

export async function POST(req: NextRequest) {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json({ success: false, error: 'Gemini API key not configured' }, { status: 400 });
    }

    const body = await req.json();
    const { imageUrl, backgroundScene, lightingStyle } = body;

    if (!imageUrl) {
      return NextResponse.json({ success: false, error: 'Product image is required' }, { status: 400 });
    }

    // Check cache
    const cacheKey = await hashPayload(JSON.stringify({ imageUrl: imageUrl.substring(0, 200), backgroundScene, lightingStyle }));
    const cached = getCached(cacheKey);
    if (cached) {
      const encoder = new TextEncoder();
      const cachedStream = new ReadableStream({
        start(controller) {
          controller.enqueue(encoder.encode(JSON.stringify({ status: 'Serving from cache...' }) + '\n'));
          controller.enqueue(encoder.encode(JSON.stringify({ success: true, data: cached }) + '\n'));
          controller.close();
        }
      });
      return new Response(cachedStream, {
        headers: {
          'Content-Type': 'text/event-stream',
          'Cache-Control': 'no-cache',
          'Connection': 'keep-alive',
        }
      });
    }

    const scenePrompts: Record<string, string> = {
      'Studio White': 'a seamless pure white studio backdrop with soft box lighting and a subtle drop shadow beneath the product',
      'Lifestyle Home': 'a luxury lifestyle setting with warm marble surface, soft natural window light, and shallow depth of field',
      'Outdoor Nature': 'a natural outdoor setting with golden hour lighting, soft bokeh greenery in the background',
      'Urban Street': 'an urban concrete surface with moody ambient street lighting and cinematic color grade',
      'Luxury Minimal': 'a dark slate surface with dramatic side lighting, deep shadows and high contrast luxury editorial feel',
      'E-commerce Clean': 'a pure white background with perfectly even lighting, no shadows, clean e-commerce style',
    };

    let scenePrompt = '';
    if (backgroundScene in scenePrompts) {
      scenePrompt = scenePrompts[backgroundScene];
    } else {
      scenePrompt = `${backgroundScene} professional product photography commercial quality studio grade`;
    }

    const prompt = `Remove the background from this product completely. Replace it with: ${scenePrompt}. Make it look like a professional commercial product photograph. Preserve all product details, edges, and original lighting on the product itself. Output only the final composited image.`;

    const match = imageUrl.match(/^data:([^;]+);base64,(.+)$/);
    if (!match) {
      return NextResponse.json({ success: false, error: 'Invalid product image format. Base64 expected.' }, { status: 400 });
    }
    const mimeType = match[1];
    const base64Data = match[2];

    const encoder = new TextEncoder();
    const stream = new ReadableStream({
      async start(controller) {
        try {
          const sendStatus = (status: string) => {
            controller.enqueue(encoder.encode(JSON.stringify({ status }) + '\n'));
          };

          sendStatus('Analysing product...');
          await new Promise(resolve => setTimeout(resolve, 1000));

          sendStatus('Removing background...');
          await new Promise(resolve => setTimeout(resolve, 1500));

          sendStatus('Generating scene...');

          const geminiRes = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/gemini-3-pro-image:generateContent?key=${apiKey}`,
            {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                contents: [
                  {
                    parts: [
                      { inlineData: { mimeType, data: base64Data } },
                      { text: prompt }
                    ]
                  }
                ],
                generationConfig: {
                  responseModalities: ['IMAGE', 'TEXT'],
                  temperature: 1.0,
                },
              })
            }
          );

          if (!geminiRes.ok) {
            const errText = await geminiRes.text();
            throw new Error(`Gemini 3 Pro Image error: ${geminiRes.status} ${errText}`);
          }

          const data = await geminiRes.json();
          const part = data.candidates?.[0]?.content?.parts?.find(
            (p: { inlineData?: { mimeType: string; data: string } }) => p.inlineData
          );
          if (!part?.inlineData?.data) {
            throw new Error('No image was generated by Gemini 3 Pro Image');
          }

          sendStatus('Done');

          const finalImageUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
          const result = { imageUrl: finalImageUrl };
          setCached(cacheKey, result, 86400);

          controller.enqueue(encoder.encode(JSON.stringify({ success: true, data: result }) + '\n'));
          controller.close();
        } catch (error: unknown) {
          const message = error instanceof Error ? error.message : 'Unknown error';
          controller.enqueue(encoder.encode(JSON.stringify({ success: false, error: message }) + '\n'));
          controller.close();
        }
      }
    });

    return new Response(stream, {
      headers: {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
      }
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json({ success: false, error: message }, { status: 503 });
  }
}
